### ISSUE TITLE
ValueError perands count not be broadcast together with shapes (xxxx, xxxx)

### ISSUE THREAD

**Issue by eddydowle** [COMBINE-lab/grouper#7]
Hi,
I can successfully get grouper to run on the example dataset but when I try it on my own I get an error 'ValueError: operands could not be broadcast together with shapes (3126384,) (6274562,) ' Which seems to have something to do with pandas.

The transcriptome is very large. I built it using several different runs and merged with dddupe to remove exact matches. Is there an upper limit to the number of transcripts you can have?

/homes/eddydowle/.local/bin/Grouper:46: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(yamCfg)
2019-06-03 21:11:46 mage11 root[70635] INFO Building multiple alignment graph
2019-06-03 21:11:51 mage11 root[70635] INFO quant file: just_trinity/EW25_salmon/quant.sf; eq file: just_trinity/EW25_salmon/aux_info//eq_classes.txt; # tran = 3126384; # eq = 2382604
Traceback (most recent call last):
  File "/homes/eddydowle/.local/bin/Grouper", line 238, in <module>
    processQuant()
  File "/homes/eddydowle/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/homes/eddydowle/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/homes/eddydowle/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/homes/eddydowle/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/homes/eddydowle/.local/bin/Grouper", line 121, in processQuant
    eqnet.buildNetFile(sampleDirs, netFile, cutoff, auxDir)
  File "/homes/eddydowle/.local/lib/python2.7/site-packages/grouper/eqnet.py", line 52, in buildNetFile
    sumCounts = np.maximum(sumCounts, estCount)
ValueError: operands could not be broadcast together with shapes (3126384,) (6274562,)

**Comment by maliklaraib** [comment]
Hi, 
I've not run into this problem before so I can not put a limit on the size. If there's a lot of contigs in the assembly, I can image the graph getting too big and running into memory issues. However, this does not seem to be a memory error. Are all the salmon output files you pass to grouper generated using the same index/reference? Is it possible to share some of them over email so that I can reproduce the issue and help address it?

**Comment by laraib85** [comment]
Hi,
I've not run into this problem before so I can not put a limit on the size. If there's a lot of contigs in the assembly, I can image the graph getting too big and running into memory issues. However, this does not seem to be a memory error. Are all the salmon output files you pass to grouper generated using the same index/reference? Is it possible to share some of them over email so that I can reproduce the issue and help address it?

**Comment by EmilyAmor** [comment]
Hi There,

I have come across the exact same issue/error:

```
2019-06-19 12:26:39 node05 root[24673] INFO quant file: /home/estander/rauwolfia/seq2019/grouping/02_mega_transcriptome.fa_for_grouper/quant.sf; eq file: /home/estander/rauwolfia/seq2019/grouping/02_mega_transcriptome.fa_for_grouper/aux_info//eq_classes.txt; # tran = 1395754; # eq = 1581910
Traceback (most recent call last):
  File "/home/estander/.local/bin/Grouper", line 238, in <module>
    processQuant()
  File "/home/estander/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/estander/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/estander/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/estander/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/estander/.local/bin/Grouper", line 121, in processQuant
    eqnet.buildNetFile(sampleDirs, netFile, cutoff, auxDir)
  File "/home/estander/.local/lib/python2.7/site-packages/grouper/eqnet.py", line 52, in buildNetFile
    sumCounts = np.maximum(sumCounts, estCount)
ValueError: operands could not be broadcast together with shapes (1395754,) (9293458,)
``` 
My experimental setup is pretty much similar to @eddydowle ; I have a large transcriptome (1395879 contigs) created from merging smaller transcriptomes that have been dereplicated using CD-HIT-EST. This single transcriptome was used as the reference/index in salmon. Grouper was installed using python 2.7. 

My config.yaml looks as follows:

```
`conditions:
    - LeL
    - LeS
    - RS
samples:
    LeL:
        - /home/estander/rauwolfia/seq2019/grouping/02_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/05_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/06_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/25_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/26_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/27_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/29_mega_transcriptome.fa_for_grouper
    LeS:
        - /home/estander/rauwolfia/seq2019/grouping/08_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/09_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/12_mega_transcriptome.fa_for_grouper
    RS:
       	- /home/estander/rauwolfia/seq2019/grouping/19_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/20_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/21_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/22_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/23_mega_transcriptome.fa_for_grouper
        - /home/estander/rauwolfia/seq2019/grouping/24_mega_transcriptome.fa_for_grouper

outdir: mega_transcriptome.fa_grouper_worphan_nomincut
orphan: True
mincut: False
`
```

Please let me know if you require any additional information.
